---
- name: Create a test instance
  hosts: localhost
  gather_facts: False
  vars_prompt:
    - name: "number"
      prompt: "How many nodes you want to install?"
  vars:
    keypair: sutv
    instance_type: t2.micro
    security_group: default
    image: ami-19f28d4b
    wait: yes
    region: us-east-1
    count: 3 
    vpc_subnet_id: vpc-05467343e7f4b257a
    assign_public_ip: no
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-03d05ee97190c50f5
         assign_public_ip: yes
      register: ec2
