---
- name: Create a test instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: my_keypair
    instance_type: t2.micro
    security_group: my_securitygroup
    image: my_ami_id
    wait: yes
    region: us-east-1
    count: 3
    vpc_subnet_id: vpc-05467343e7f4b257a
    assign_public_ip: yes
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-29e63245
         assign_public_ip: yes
      register: ec2
